[package]
name = "chat_server"
version = "0.1.0"
authors = ["Daniel Hedrén <danielhedren@gmail.com>"]

[dependencies]
ws = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
pbkdf2 = "*"
crossbeam = "*"
crossbeam-utils = "*"
chashmap = "*"
evmap = "*"